### ISSUE TITLE
backIcon的颜色怎么设置？

### ISSUE THREAD

**Issue by danna88** [listenzz/hybrid-navigation#166]
现在我需要用自己的image作为返回按钮，图片是橙色的，但是设置backIcon后，效果是黑色的

**Comment by danna88** [comment]
哦，我发现topBarTintColor可以设置，但是这样是不是把所有导航按钮都统一成一个颜色了？

**Comment by listenzz** [comment]
@danna88 通过 Garden 是设置全局的，通过 navigationItem 是设置特定页面的

**Comment by danna88** [comment]
嗯，上面的问题了解了。试过可以修改文字按钮颜色。不过。。
今天npm install 之后，这样设置崩了
rightBarButtonItem: {
      icon: {uri: fontUri({name: iconName.scan, fontFamily: fontFamilys.Iconfont})},
    }
我重新安装本库试试。

**Comment by danna88** [comment]
依然不行，会崩溃，错误信息如下：
```
2020-05-13 11:18:28.047 19562-19562/com.westone.wstcode.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.westone.wstcode.test, PID: 19562
    java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1197)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1164)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1114)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1075)
        at com.navigation.androidx.DrawableUtils.filepathFromFont(DrawableUtils.java:125)
        at com.navigation.androidx.DrawableUtils.filepathFromFont(DrawableUtils.java:95)
        at com.navigation.androidx.DrawableUtils.fromUri(DrawableUtils.java:56)
        at com.navigation.androidx.AwesomeToolbar.drawableFromBarButtonItem(AwesomeToolbar.java:419)
        at com.navigation.androidx.AwesomeToolbar.setButton(AwesomeToolbar.java:353)
        at com.navigation.androidx.AwesomeToolbar.setRightButton(AwesomeToolbar.java:314)
        at com.navigation.androidx.AwesomeFragment.setRightBarButtonItem(AwesomeFragment.java:1459)
        at com.navigationhybrid.Garden.setRightBarButtonItem(Garden.java:155)
        at com.navigationhybrid.Garden.configureToolbar(Garden.java:109)
        at com.navigationhybrid.HybridFragment.onActivityCreated(HybridFragment.java:91)
        at com.navigationhybrid.ReactFragment.onActivityCreated(ReactFragment.java:122)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2619)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2624)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2624)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2100)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1874)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.executePendingTransactions(FragmentManagerImpl.java:183)
        at com.navigation.androidx.FragmentHelper.executePendingTransactionsSafe(FragmentHelper.java:39)
        at com.navigation.androidx.AwesomeActivity.setRootFragmentInternal(AwesomeActivity.java:107)
        at com.navigationhybrid.ReactAppCompatActivity.setRootFragmentInternal(ReactAppCompatActivity.java:120)
        at com.navigationhybrid.ReactAppCompatActivity.setActivityRootFragment(ReactAppCompatActivity.java:104)
        at com.navigationhybrid.NavigationModule.lambda$setRoot$14$NavigationModule(NavigationModule.java:127)
        at com.navigationhybrid.-$$Lambda$NavigationModule$qhpue8d2cCk7f4a1JJj_xVw2CkU.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
```

**Comment by listenzz** [comment]
需要指定宽高 { uri:, width: height:}

**Comment by danna88** [comment]
但是那个icon是个svg啊

**Comment by listenzz** [comment]
uri 的格式不对，应该是 font://fontFamily/glyph/fontSize/color

**Comment by danna88** [comment]
我那个方法里最后返回的就是你说的那种格式，只是我自己又封装了下
