### ISSUE TITLE
1.7.2版本android 启动报错 Method setCurrentState must be called on the main thread

### ISSUE THREAD

**Issue by dppo** [listenzz/hybrid-navigation#190]
`E/unknown:ReactNative: Exception in native call
    java.lang.IllegalStateException: Method setCurrentState must be called on the main thread
        at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
        at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:120)
        at com.reactnative.hybridnavigation.NavigationModule.<init>(NavigationModule.java:55)
        at com.reactnative.hybridnavigation.HybridNavigationPackage.createNativeModules(HybridNavigationPackage.java:24)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1240)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1023)
        at java.lang.Thread.run(Thread.java:919)
W/Gralloc3: mapper 3.x is not supported
`

**Comment by listenzz** [comment]
@dppo 请问你使用的 RN 版本和 androidx 版本是什么？

**Comment by dppo** [comment]
> @dppo 请问你使用的 RN 版本和 androidx 版本是什么？

抱歉，经过排查，应该是其他代码影响的。跟hybrid-navigation无关

**Comment by dppo** [comment]
> @dppo 请问你使用的 RN 版本和 androidx 版本是什么？
react-native版本0.64.1，hybrid-navigation版本1.7.3，依旧报错

发现应该还是跟本库有关，报错都跟不在UI线程有关。

yarn add @dppo/react-native-photo-picker，使用这个库，我这demo毕现

![报错截图](https://user-images.githubusercontent.com/85061291/122081168-76654600-ce31-11eb-919a-348c4699fbcb.JPG)

自己简单修改了下，NavigationModule，GardenModule，这两个类按图修改后，能正常运行，但是不确定是否有其他问题，能否针对这个问题，统一修复下？

![WX20210615-233013](https://user-images.githubusercontent.com/85061291/122081499-baf0e180-ce31-11eb-8ec6-ac06f4d452be.png)
![WX20210615-233036](https://user-images.githubusercontent.com/85061291/122081507-bd533b80-ce31-11eb-8cc0-6925df81a96f.png)

**Comment by dppo** [comment]
https://github.com/dppo/react-native-template-dppo.git

也可以直接运行这个里面的demo

**Comment by listenzz** [comment]
@dppo 原因是某个库使用了 

```
implementation 'androidx.appcompat:appcompat:1.3.0'
```

而 appcompat：1.3 增加了对 Lifecycle 相关方法是否在主线程执行的检查

同时将 DialogFragment 的某些包可见方法改为私有

兼容 appcompat:1.3 需要点时间

你是否可以将 appcompat 降级为 1.2 ？

**Comment by dppo** [comment]
> @dppo 原因是某个库使用了
> 
> ```
> implementation 'androidx.appcompat:appcompat:1.3.0'
> ```
> 
> 而 appcompat：1.3 增加了对 Lifecycle 相关方法是否在主线程执行的检查
> 
> 同时将 DialogFragment 的某些包可见方法改为私有
> 
> 兼容 appcompat:1.3 需要点时间
> 
> 你是否可以将 appcompat 降级为 1.2 ？

好的，我试一下

**Comment by dppo** [comment]
> @dppo 原因是某个库使用了
> 
> ```
> implementation 'androidx.appcompat:appcompat:1.3.0'
> ```
> 
> 而 appcompat：1.3 增加了对 Lifecycle 相关方法是否在主线程执行的检查
> 
> 同时将 DialogFragment 的某些包可见方法改为私有
> 
> 兼容 appcompat:1.3 需要点时间
> 
> 你是否可以将 appcompat 降级为 1.2 ？

请问下，是否有计划升级appcompat到1.3版本？   最近发现不少第三方包都更新了，导致涉及到不少冲突。

**Comment by listenzz** [comment]
@dppo 没有计划，除非 ReactNative 官方使用的是 1.3

> 请问下，是否有计划升级appcompat到1.3版本？ 最近发现不少第三方包都更新了，导致涉及到不少冲突。

**Comment by 8BallBomBom** [comment]
Getting the same error after upgrading to RN 0.66.0-rc.4, was mainly testing realm with hermes.

```
Exception in native call
java.lang.IllegalStateException: Method setCurrentState must be called on the main thread
	at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
	at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:120)
	at com.reactnative.hybridnavigation.NavigationModule.<init>(NavigationModule.java:55)
	at com.reactnative.hybridnavigation.HybridNavigationPackage.createNativeModules(HybridNavigationPackage.java:24)
	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1425)
	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1396)
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1287)
	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by 8BallBomBom** [comment]
Also can't find any packages in node_modules using androidx.appcompat:appcompat 1.3.0
Will try a fresh project to see if i can find the culprit.

**Comment by 8BallBomBom** [comment]
Alrighty so it would seem a change in RN 0.66 is forcing androidx.appcompat:appcompat to go as far as 1.3.0 but i'm having trouble finding exactly what but still investigating either way.

**Comment by dppo** [comment]
0.66.1版本，新创建项目集成这个库直接报错了，应该是RN已经使用androidx.appcompat:appcompat  1.3.0 版本了，希望作者更新下支持

**Comment by listenzz** [comment]
已支持，since v2.7.0
