### ISSUE TITLE
建议： 能不能出个Demo 能用的？ 按照教程来搞完全报错

### ISSUE THREAD

**Issue by jeesk** [listenzz/hybrid-navigation#237]
1.    按照你的https://todoit.tech/rn/hybrid-navigation/integration-react.html#ios-%E9%A1%B9%E7%9B%AE%E9%85%8D%E7%BD%AE ， 来配置， 报错这个
```
  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rntest/com.rntest.MainActivity}: java.lang.IllegalStateException: Must call ReactBridgeManager#install first
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.lang.IllegalStateException: Must call ReactBridgeManager#install first
        at com.reactnative.hybridnavigation.ReactBridgeManager.checkReactNativeHost(ReactBridgeManager.java:105)
        at com.reactnative.hybridnavigation.ReactBridgeManager.getReactNativeHost(ReactBridgeManager.java:88)
        at com.reactnative.hybridnavigation.ReactAppCompatActivityDelegate.getReactNativeHost(ReactAppCompatActivityDelegate.java:68)
        at com.reactnative.hybridnavigation.ReactAppCompatActivity.getReactNativeHost(ReactAppCompatActivity.java:265)
        at com.rntest.MainActivity.onCreate(MainActivity.java:28)
        at android.app.Activity.performCreate(Activity.java:7963)
        at android.app.Activity.performCreate(Activity.java:7952)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8167) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 
```
2. 项目里面的example 怎么使用的？

**Comment by listenzz** [comment]
1. 
<img width="797" alt="image" src="https://user-images.githubusercontent.com/4386370/182515649-19c00477-3652-464e-b0b4-3fd036fb77aa.png">

2. 查看根目录下的 package.json。

在根目录下运行

```sh
yarn install
npm start
```

如果熟悉原生开发，使用 Android Studio 打开 example/android，像运行原生应用那样运行它。
或者打开一个新的终端，然后运行

```sh
npm run run:android
```

**Comment by jeesk** [comment]
> <img alt="image" width="797" src="https://user-images.githubusercontent.com/4386370/182515649-19c00477-3652-464e-b0b4-3fd036fb77aa.png">
> 
> 2. 查看根目录下的 package.json。
> 
> 在根目录下运行
> 
> ```shell
> yarn install
> npm start
> ```
> 
> 如果熟悉原生开发，使用 Android Studio 打开 example/android，像运行原生应用那样运行它。 或者打开一个新的终端，然后运行
> 
> ```shell
> npm run run:android
> ```

ok谢谢。 已经看到了。

**Comment by listenzz** [comment]
Android 需要改一下，才能用命令行跑起来，我稍后提交代码

<img width="993" alt="image" src="https://user-images.githubusercontent.com/4386370/182517202-f15c4cc9-4234-43e5-9226-b7b420d7f5ba.png">

**Comment by listenzz** [comment]
更新了项目和文档，现在可以按照[这个指引](https://todoit.tech/rn/hybrid-navigation/#%E8%BF%90%E8%A1%8C-example-%E9%A1%B9%E7%9B%AE)运行 example 项目。
